services:
  mysql:
    image: mysql:8.0.45-debian
    container_name: mysql
    ports:
      - "3308:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: MateoDev2026!
      MYSQL_DATABASE: Registro
      MYSQL_USER: app_user
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-scripts/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
volumes:
  mysql_data: